In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import time
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error, r2_score, f1_score
import numpy as np
from sklearn.ensemble import BaggingClassifier ,ExtraTreesClassifier,BaggingRegressor ,RandomForestClassifier



In [18]:

# Load the dataset
df = pd.read_csv("healthcare_dataset.csv")
df.head()


Name  Age  Gender Blood Type Medical Condition Date of Admission  \
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31   
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22   
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18   
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19   

             Doctor                    Hospital Insurance Provider  \
0     Matthew Smith             Sons and Miller         Blue Cross   
1   Samantha Davies                     Kim Inc           Medicare   
2  Tiffany Mitchell                    Cook PLC              Aetna   
3       Kevin Wells  Hernandez Rogers and Vang,           Medicare   
4    Kathleen Hanna                 White-White              Aetna   

   Billing Amount  Room Number Admission Type Discharge Date   Medication  \
0    18856.281306          328         Urgent     2024-02-02  Paracetamol   
1    33643.327287          265      Emergency     2019-08-26    Ibuprofen   
2    27955.096079          205      Emergency     2022-10-07      Aspirin   
3    37909.782410          450       Elective     2020-12-18    Ibuprofen   
4    14238.317814          458         Urgent     2022-10-09   Penicillin   

   Test Results  
0        Normal  
1  Inconclusive  
2        Normal  
3      Abnormal  
4      Abnormal

In [19]:
df = df.drop(columns=['Name', 'Date of Admission', 'Discharge Date'])
dtype=df.dtypes
df.head()

Age  Gender Blood Type Medical Condition            Doctor  \
0   30    Male         B-            Cancer     Matthew Smith   
1   62    Male         A+           Obesity   Samantha Davies   
2   76  Female         A-           Obesity  Tiffany Mitchell   
3   28  Female         O+          Diabetes       Kevin Wells   
4   43  Female        AB+            Cancer    Kathleen Hanna   

                     Hospital Insurance Provider  Billing Amount  Room Number  \
0             Sons and Miller         Blue Cross    18856.281306          328   
1                     Kim Inc           Medicare    33643.327287          265   
2                    Cook PLC              Aetna    27955.096079          205   
3  Hernandez Rogers and Vang,           Medicare    37909.782410          450   
4                 White-White              Aetna    14238.317814          458   

  Admission Type   Medication  Test Results  
0         Urgent  Paracetamol        Normal  
1      Emergency    Ibuprofen  Inconclusive  
2      Emergency      Aspirin        Normal  
3       Elective    Ibuprofen      Abnormal  
4         Urgent   Penicillin      Abnormal

In [20]:
df

Age  Gender Blood Type Medical Condition            Doctor  \
0       30    Male         B-            Cancer     Matthew Smith   
1       62    Male         A+           Obesity   Samantha Davies   
2       76  Female         A-           Obesity  Tiffany Mitchell   
3       28  Female         O+          Diabetes       Kevin Wells   
4       43  Female        AB+            Cancer    Kathleen Hanna   
...    ...     ...        ...               ...               ...   
55495   42  Female         O+            Asthma     Joshua Jarvis   
55496   61  Female        AB-           Obesity   Taylor Sullivan   
55497   38  Female         B+      Hypertension    Joe Jacobs DVM   
55498   43    Male         O-         Arthritis    Kimberly Curry   
55499   53  Female         O+         Arthritis     Dennis Warren   

                           Hospital Insurance Provider  Billing Amount  \
0                   Sons and Miller         Blue Cross    18856.281306   
1                           Kim Inc           Medicare    33643.327287   
2                          Cook PLC              Aetna    27955.096079   
3        Hernandez Rogers and Vang,           Medicare    37909.782410   
4                       White-White              Aetna    14238.317814   
...                             ...                ...             ...   
55495                Jones-Thompson         Blue Cross     2650.714952   
55496                  Tucker-Moyer              Cigna    31457.797307   
55497  and Mahoney Johnson Vasquez,   UnitedHealthcare    27620.764717   
55498      Jackson Todd and Castro,           Medicare    32451.092358   
55499                Henry Sons and              Aetna     4010.134172   

       Room Number Admission Type   Medication  Test Results  
0              328         Urgent  Paracetamol        Normal  
1              265      Emergency    Ibuprofen  Inconclusive  
2              205      Emergency      Aspirin        Normal  
3              450       Elective    Ibuprofen      Abnormal  
4              458         Urgent   Penicillin      Abnormal  
...            ...            ...          ...           ...  
55495          417       Elective   Penicillin      Abnormal  
55496          316       Elective      Aspirin        Normal  
55497          347         Urgent    Ibuprofen      Abnormal  
55498          321       Elective    Ibuprofen      Abnormal  
55499          448         Urgent    Ibuprofen      Abnormal  

[55500 rows x 12 columns]

In [21]:
# Encode categorical features
for i in range(df.shape[1]):
    if df.dtypes[df.columns[i]]=="O":
        label_encoder =LabelEncoder()
        df[df.columns[i]]=label_encoder.fit_transform(df[df.columns[i]])
df


Age  Gender  Blood Type  Medical Condition  Doctor  Hospital  \
0       30       1           5                  2   26612     29933   
1       62       1           0                  5   33648     16012   
2       76       0           1                  5   37828      5473   
3       28       0           6                  3   22511     12317   
4       43       0           2                  2   21259     33598   
...    ...     ...         ...                ...     ...       ...   
55495   42       0           6                  1   20003     15553   
55496   61       0           3                  5   37149     31722   
55497   38       0           4                  4   18550     37408   
55498   43       1           7                  0   22665     14329   
55499   53       0           6                  0   10782     12207   

       Insurance Provider  Billing Amount  Room Number  Admission Type  \
0                       1    18856.281306          328               2   
1                       3    33643.327287          265               1   
2                       0    27955.096079          205               1   
3                       3    37909.782410          450               0   
4                       0    14238.317814          458               2   
...                   ...             ...          ...             ...   
55495                   1     2650.714952          417               0   
55496                   2    31457.797307          316               0   
55497                   4    27620.764717          347               2   
55498                   3    32451.092358          321               0   
55499                   0     4010.134172          448               2   

       Medication  Test Results  
0               3             2  
1               1             1  
2               0             2  
3               1             0  
4               4             0  
...           ...           ...  
55495           4             0  
55496           0             2  
55497           1             0  
55498           1             0  
55499           1             0  

[55500 rows x 12 columns]

In [23]:
target_column = 'Admission Type'
y = df[target_column]
y = LabelEncoder().fit_transform(y)
y

array([2, 1, 1, ..., 2, 0, 2])

In [24]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=[target_column]), y, test_size=0.2, random_state=42)


In [25]:
from sklearn.ensemble import AdaBoostClassifier
ada_model = AdaBoostClassifier(n_estimators=50, random_state=42)
start_time = time.time()
ada_model.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred = ada_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Model: AdaBoostClassifier")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)


Model: AdaBoostClassifier
Training Time: 5.47 seconds
Accuracy: 33.99%
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.46      0.39      3664
           1       0.34      0.22      0.26      3656
           2       0.35      0.34      0.35      3780

    accuracy                           0.34     11100
   macro avg       0.34      0.34      0.33     11100
weighted avg       0.34      0.34      0.33     11100

Confusion Matrix:
[[1684  778 1202]
 [1663  797 1196]
 [1687  801 1292]]


In [26]:
# Section 2: AdaBoostRegressor
target_column_regression = 'Billing Amount'
y_reg = df[target_column_regression]

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(df.drop(columns=[target_column_regression]), y_reg, test_size=0.2, random_state=42)

from sklearn.ensemble import AdaBoostRegressor
ada_reg_model = AdaBoostRegressor(n_estimators=50, random_state=42)
start_time = time.time()
ada_reg_model.fit(X_train_reg, y_train_reg)
training_time_reg = time.time() - start_time

y_pred_reg = ada_reg_model.predict(X_test_reg)

from sklearn.metrics import mean_squared_error, r2_score
tolerance = 0.1
accuracy_within_tolerance = sum(abs(y_pred_reg - y_test_reg) <= (tolerance * y_test_reg)) / len(y_test_reg)

mse = mean_squared_error(y_test_reg, y_pred_reg)
r2 = r2_score(y_test_reg, y_pred_reg)

print("\nModel: AdaBoostRegressor")
print(f"Training Time: {training_time_reg:.2f} seconds")
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")
print(f"Accuracy {tolerance * 100}%: {accuracy_within_tolerance * 100:.2f}%")


Model: AdaBoostRegressor
Training Time: 1.02 seconds
Mean Squared Error: 198996442.01417089
R^2 Score: -0.00043762046886475225
Accuracy 10.0%: 10.36%


In [27]:

# Section 3: Decision Tree Classifier
# ------------------------------------
from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier()
start_time = time.time()
tree_model.fit(X_train, y_train)
y_pred = tree_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("\nModel: Decision Tree Classifier")
print(f"Training Time: {time.time() - start_time:.2f} seconds")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)


Model: Decision Tree Classifier
Training Time: 1.66 seconds
Accuracy: 42.50%
Classification Report:
              precision    recall  f1-score   support

           0       0.42      0.44      0.43      3664
           1       0.42      0.42      0.42      3656
           2       0.43      0.42      0.42      3780

    accuracy                           0.42     11100
   macro avg       0.43      0.43      0.42     11100
weighted avg       0.43      0.42      0.42     11100

Confusion Matrix:
[[1603 1028 1033]
 [1074 1534 1048]
 [1139 1061 1580]]


In [35]:

# Section 4: Support Vector Classifier (SVC)
# -------------------------------------------
from sklearn.svm import SVC

svc_model = SVC()
start_time = time.time()
svc_model.fit(X_train, y_train)
y_pred = svc_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("\nModel: Support Vector Classifier (SVC)")
print(f"Training Time: {time.time() - start_time:.2f} seconds")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)


KeyboardInterrupt: 

In [ ]:
# Section 5: Linear Regression
# -----------------------------
import time
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()

start_time = time.time()
model.fit(X_train, y_train)
elapsed_time = time.time() - start_time

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nModel: Linear Regression")
print(f"Mean Squared Error: {mse:.2f}")
print(f"Accuracy: {accuracy:.2f}%")
print(f"Time Taken: {elapsed_time:.2f} seconds")


In [29]:

# Section 6: KNeighborsClassifier
# --------------------------------
import time
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

model = KNeighborsClassifier()

start_time = time.time()
model.fit(X_train, y_train)
elapsed_time = time.time() - start_time

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred) * 100
f1 = f1_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)
worst_case = np.min(np.diag(conf_matrix))

print("\nModel: KNeighborsClassifier")
print(f"Accuracy: {accuracy:.2f}%")
print(f"F1 Score: {f1:.2f}")
print(f"Time Taken: {elapsed_time:.2f} seconds")
print(f"Worst Case: {worst_case}")


Model: KNeighborsClassifier
Accuracy: 36.42%
F1 Score: 0.36
Time Taken: 0.17 seconds
Worst Case: 985


In [30]:
# Section 7: Gaussian Naive Bayes
# --------------------------------
import time
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

nb_classifier = GaussianNB()

start_time = time.time()
nb_classifier.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred_nb = nb_classifier.predict(X_test)

accuracy_nb = accuracy_score(y_test, y_pred_nb) * 100
report_nb = classification_report(y_test, y_pred_nb)

print("\nModel: Gaussian Naive Bayes")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy_nb:.2f}%")
print(f"Classification Report:\n{report_nb}")



Model: Gaussian Naive Bayes
Training Time: 0.04 seconds
Accuracy: 33.71%
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.54      0.41      3664
           1       0.33      0.13      0.19      3656
           2       0.35      0.35      0.35      3780

    accuracy                           0.34     11100
   macro avg       0.34      0.34      0.31     11100
weighted avg       0.34      0.34      0.31     11100



In [31]:
# # Section 8: Polynomial Logistic Regression
# # -----------------------------------------
import time
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

model = Pipeline([('poly', PolynomialFeatures(degree=2)), ('logistic', LogisticRegression(max_iter=1000))])

start_time = time.time()
model.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred_poly = model.predict(X_test)

accuracy_poly = accuracy_score(y_test, y_pred_poly) * 100
report_poly = classification_report(y_test, y_pred_poly)

print("\nModel: Polynomial Logistic Regression")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy_poly:.2f}%")
print(f"Classification Report:\n{report_poly}")



Model: Polynomial Logistic Regression
Training Time: 2.39 seconds
Accuracy: 32.90%
Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.65      0.44      3664
           1       0.32      0.19      0.24      3656
           2       0.35      0.15      0.21      3780

    accuracy                           0.33     11100
   macro avg       0.33      0.33      0.29     11100
weighted avg       0.33      0.33      0.29     11100



In [33]:
# # Section 9: StackingClassifier
# # -----------------------------
import time
from sklearn.ensemble import StackingClassifier, RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

base_models = [('rf', RandomForestClassifier(random_state=42)), ('gb', GradientBoostingClassifier(random_state=42))]
stacking_clf = StackingClassifier(estimators=base_models, final_estimator=LogisticRegression(), cv=5)

start_time = time.time()
stacking_clf.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred_stack = stacking_clf.predict(X_test)

accuracy_stack = accuracy_score(y_test, y_pred_stack) * 100
report_stack = classification_report(y_test, y_pred_stack)

print("\nModel: StackingClassifier")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy_stack:.2f}%")
print(f"Classification Report:\n{report_stack}")



Model: StackingClassifier
Training Time: 336.07 seconds
Accuracy: 43.72%
Classification Report:
              precision    recall  f1-score   support

           0       0.42      0.46      0.44      3664
           1       0.45      0.42      0.43      3656
           2       0.44      0.43      0.44      3780

    accuracy                           0.44     11100
   macro avg       0.44      0.44      0.44     11100
weighted avg       0.44      0.44      0.44     11100



In [34]:

# Section 10: BaggingClassifier
# ----------------------------
bagging_model = BaggingClassifier(n_estimators=50, random_state=42)
start_time = time.time()
bagging_model.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred = bagging_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("\nModel: BaggingClassifier")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)



Model: BaggingClassifier
Training Time: 37.12 seconds
Accuracy: 43.98%
Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.48      0.45      3664
           1       0.44      0.42      0.43      3656
           2       0.45      0.42      0.44      3780

    accuracy                           0.44     11100
   macro avg       0.44      0.44      0.44     11100
weighted avg       0.44      0.44      0.44     11100

Confusion Matrix:
[[1771  972  921]
 [1154 1535  967]
 [1215  989 1576]]

Model: BaggingRegressor
Training Time: 26.15 seconds
Mean Squared Error: 183106918.54058793
R^2 Score: 0.07944560203198525
Accuracy within 10.0% tolerance: 12.59%

Model: ExtraTreesClassifier
Training Time: 8.69 seconds
Accuracy: 44.35%
Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.47      0.45      3664
           1       0.45      0.43      0.44      3656
           2       0.46    

/usr/local/lib/python3.10/dist-packages/sklearn/experimental/enable_hist_gradient_boosting.py:15: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(



Model: HistGradientBoostingClassifier
Training Time: 1.08 seconds
Accuracy: 18.19%
Classification Report:
              precision    recall  f1-score   support

           0       0.17      0.14      0.15      1915
           1       0.19      0.15      0.17      1847
           2       0.19      0.15      0.17      1871
           3       0.17      0.22      0.19      1822
           4       0.18      0.23      0.20      1788
           5       0.19      0.21      0.20      1857

    accuracy                           0.18     11100
   macro avg       0.18      0.18      0.18     11100
weighted avg       0.18      0.18      0.18     11100



In [39]:

# Section 11: BaggingRegressor
# ----------------------------
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import time

target_column_regression = 'Billing Amount'
y_reg = df[target_column_regression]
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(df.drop(columns=[target_column_regression]), y_reg, test_size=0.2, random_state=42)

bagging_reg_model = BaggingRegressor(n_estimators=50, random_state=42)
start_time = time.time()
bagging_reg_model.fit(X_train_reg, y_train_reg)
training_time_reg = time.time() - start_time

y_pred_reg = bagging_reg_model.predict(X_test_reg)

tolerance = 0.1
accuracy_within_tolerance = sum(abs(y_pred_reg - y_test_reg) <= (tolerance * y_test_reg)) / len(y_test_reg)

mse = mean_squared_error(y_test_reg, y_pred_reg)
r2 = r2_score(y_test_reg, y_pred_reg)

print("\nModel: BaggingRegressor")
print(f"Training Time: {training_time_reg:.2f} seconds")
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")
print(f"Accuracy within {tolerance * 100}% tolerance: {accuracy_within_tolerance * 100:.2f}%")




Model: BaggingRegressor
Training Time: 26.24 seconds
Mean Squared Error: 183106918.54058793
R^2 Score: 0.07944560203198525
Accuracy within 10.0% tolerance: 12.59%


In [38]:


# Section 12: ExtraTreesClassifier
# -------------------------------
extra_trees_model = ExtraTreesClassifier(n_estimators=100, random_state=42)
start_time = time.time()
extra_trees_model.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred = extra_trees_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("\nModel: ExtraTreesClassifier")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:")
print(report)
print("Confusion Matrix:")
print(conf_matrix)



Model: ExtraTreesClassifier
Training Time: 7.09 seconds
Accuracy: 30.05%
Classification Report:
              precision    recall  f1-score   support

           0       0.29      0.29      0.29      1915
           1       0.31      0.32      0.32      1847
           2       0.32      0.29      0.30      1871
           3       0.28      0.30      0.29      1822
           4       0.29      0.30      0.29      1788
           5       0.32      0.30      0.31      1857

    accuracy                           0.30     11100
   macro avg       0.30      0.30      0.30     11100
weighted avg       0.30      0.30      0.30     11100

Confusion Matrix:
[[564 302 244 284 264 257]
 [261 598 239 276 254 219]
 [283 268 547 271 248 254]
 [297 259 224 539 275 228]
 [282 236 236 258 529 247]
 [278 264 230 272 255 558]]


In [37]:

# Section 13: RandomForestClassifier
# ---------------------------------
import time
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

features = df.drop(columns=['Medical Condition', 'Doctor', 'Hospital', 'Medication'])
target = df['Medical Condition']
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

rf_classifier = RandomForestClassifier(random_state=42)

start_time = time.time()
rf_classifier.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("\nModel: RandomForestClassifier")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Classification Report:\n{report}")




Model: RandomForestClassifier
Training Time: 11.37 seconds
Accuracy: 29.61%
Classification Report:
              precision    recall  f1-score   support

           0       0.29      0.30      0.29      1915
           1       0.29      0.31      0.30      1847
           2       0.31      0.29      0.30      1871
           3       0.28      0.29      0.28      1822
           4       0.29      0.30      0.29      1788
           5       0.32      0.30      0.31      1857

    accuracy                           0.30     11100
   macro avg       0.30      0.30      0.30     11100
weighted avg       0.30      0.30      0.30     11100



In [36]:

# Section 14: HistGradientBoostingClassifier
import time
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

hgb_classifier = HistGradientBoostingClassifier(random_state=42)

start_time = time.time()
hgb_classifier.fit(X_train, y_train)
training_time = time.time() - start_time

y_pred_hgb = hgb_classifier.predict(X_test)

accuracy_hgb = accuracy_score(y_test, y_pred_hgb) * 100
report_hgb = classification_report(y_test, y_pred_hgb)

print("\nModel: HistGradientBoostingClassifier")
print(f"Training Time: {training_time:.2f} seconds")
print(f"Accuracy: {accuracy_hgb:.2f}%")
print(f"Classification Report:\n{report_hgb}")

\

SyntaxError: incomplete input (<ipython-input-36-3a01d161770c>, line 23)