In [27]:
import numpy as py
import pandas as pd
df = pd.read_csv('Salary_Data.csv')
df.head()
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train ,y_test =train_test_split(x,y,test_size=0.30,random_state=42)
from sklearn.linear_model import LinearRegression
lr=LinearRegression().fit(x_train,y_train)
y_pred = lr.predict(x_test)
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,mean_absolute_percentage_error
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))
print(mean_absolute_percentage_error(y_test,y_pred))


37784662.46621314
5161.328710400183
0.9414466227178214
0.06647907533756252


In [33]:
# Import necessary libraries
import numpy as np  # Changed 'py' to 'np' for numpy as it's a common convention
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

# Load the dataset
df = pd.read_csv('50_Startups.csv')

# Display the first few rows of the dataframe
print(df.head())

# Separate features and target variable
x = df.iloc[:, :-1].values  # Features (all columns except the last one)
y = df.iloc[:, -1].values   # Target variable (the last column)

# Encode categorical features
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [3])],  # Apply OneHotEncoder to the 4th column (index 3)
    remainder='passthrough'  # Leave other columns unchanged
)
x = ct.fit_transform(x)
xx=x[:,0:7 ]

# Standardize the features
sc = StandardScaler()
xx = sc.fit_transform(xx)

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(xx, y, test_size=0.3, random_state=42)

# Train the Linear Regression model
lr = LinearRegression().fit(x_train, y_train)

# Make predictions on the test set
y_pred = lr.predict(x_test)

# Evaluate the model
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Absolute Percentage Error:", mean_absolute_percentage_error(y_test, y_pred))


   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
Mean Squared Error: 84826955.035334
Mean Absolute Error: 7395.433531523905
R2 Score: 0.9397108063355787
Mean Absolute Percentage Error: 0.08929865344173579


In [40]:
# Import necessary libraries
import numpy as np  # Use 'np' for numpy
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

# Load the dataset
df = pd.read_csv('50_Startups.csv')

# Display the first few rows of the dataframe
print(df.head())

# Separate features and target variable
x = df.iloc[:, :-1].values  # Features (all columns except the last one)
y = df.iloc[:, -1].values   # Target variable (the last column)

# Encode categorical features
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [3])],  # Apply OneHotEncoder to the 4th column (index 3)
    remainder='passthrough'  # Leave other columns unchanged
)
x = ct.fit_transform(x)
xx=x[:,0:7 ]
# Create polynomial features
poly = PolynomialFeatures(degree=6)  # Create polynomial features of degree 2
x_poly = poly.fit_transform(xx)  # Transform the features

# Standardize the features
sc = StandardScaler()
x_poly = sc.fit_transform(x_poly)  # Standardize the polynomial features

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x_poly, y, test_size=0.35, random_state=42)

# Train the Linear Regression model
lr = LinearRegression().fit(x_train, y_train)

# Make predictions on the test set
y_pred = lr.predict(x_test)

# Evaluate the model
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Absolute Percentage Error:", mean_absolute_percentage_error(y_test, y_pred))


   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
Mean Squared Error: 726440437.1383508
Mean Absolute Error: 21184.581782132063
R2 Score: 0.5353876694009497
Mean Absolute Percentage Error: 0.2415916444971201


In [54]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA


# Load the dataset
df = pd.read_csv('Social_Network_Ads.csv')

# Display the first few rows of the dataframe
print(df.head())

# Separate features and target variable
x = df.iloc[:, 1:-1].values  # Features (all columns except the last one)
y = df.iloc[:, -1].values   # Target variable (the last column)

# Encode categorical features (assuming there is a categorical feature)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],  # Adjust the indices to match categorical columns
    remainder='passthrough'
)
x = ct.fit_transform(x)

# Standardize the features
sc = StandardScaler()
x = sc.fit_transform(x)
pca = PCA(n_components=3)  # Reducing to 2 components for visualization, adjust as needed
x_pca = pca.fit_transform(x)
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.3, random_state=42)

# Train the Logistic Regression model
lr = LogisticRegression()
lr.fit(x_train, y_train)

# Make predictions on the test set
y_pred = lr.predict(x_test)

# Evaluate the model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
lr.predict(sc.fit_transform([[1,19,19000]]))

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
Accuracy Score: 0.8583333333333333
Confusion Matrix:
 [[71  2]
 [15 32]]


array([0])

In [58]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA


# Load the dataset
df = pd.read_csv('Social_Network_Ads.csv')

# Display the first few rows of the dataframe
print(df.head())

# Separate features and target variable
x = df.iloc[:, 1:-1].values  # Features (all columns except the last one)
y = df.iloc[:, -1].values   # Target variable (the last column)

# Encode categorical features (assuming there is a categorical feature)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],  # Adjust the indices to match categorical columns
    remainder='passthrough'
)
x = ct.fit_transform(x)

# Standardize the features
sc = StandardScaler()
x = sc.fit_transform(x)
pca = PCA(n_components=3)  # Reducing to 2 components for visualization, adjust as needed
x_pca = pca.fit_transform(x)
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.1, random_state=0)

# Train the Logistic Regression model
sv = SVC(kernel='linear')
sv.fit(x_train, y_train)

# Make predictions on the test set
y_pred = sv.predict(x_test)

# Evaluate the model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
sv.predict(sc.fit_transform([[1,19,19000]]))

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
Accuracy Score: 0.95
Confusion Matrix:
 [[32  0]
 [ 2  6]]


array([0])

In [59]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA


# Load the dataset
df = pd.read_csv('Social_Network_Ads.csv')

# Display the first few rows of the dataframe
print(df.head())

# Separate features and target variable
x = df.iloc[:, 1:-1].values  # Features (all columns except the last one)
y = df.iloc[:, -1].values   # Target variable (the last column)

# Encode categorical features (assuming there is a categorical feature)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],  # Adjust the indices to match categorical columns
    remainder='passthrough'
)
x = ct.fit_transform(x)

# Standardize the features
sc = StandardScaler()
x = sc.fit_transform(x)
pca = PCA(n_components=3)  # Reducing to 2 components for visualization, adjust as needed
x_pca = pca.fit_transform(x)
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.1, random_state=0)

# Train the Logistic Regression model
knn = KNeighborsClassifier(n_neighbors=4, metric='minkowski', p=2)
knn = knn.fit(x_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(x_test)

# Evaluate the model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
knn.predict(sc.fit_transform([[1,19,19000]]))

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
Accuracy Score: 0.95
Confusion Matrix:
 [[31  1]
 [ 1  7]]


array([0])

In [68]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA


# Load the dataset
df = pd.read_csv('Social_Network_Ads.csv')

# Display the first few rows of the dataframe
print(df.head())

# Separate features and target variable
x = df.iloc[:, 1:-1].values  # Features (all columns except the last one)
y = df.iloc[:, -1].values   # Target variable (the last column)

# Encode categorical features (assuming there is a categorical feature)
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],  # Adjust the indices to match categorical columns
    remainder='passthrough'
)
x = ct.fit_transform(x)

# Standardize the features
sc = StandardScaler()
x = sc.fit_transform(x)
pca = PCA(n_components=3)  # Reducing to 2 components for visualization, adjust as needed
x_pca = pca.fit_transform(x)
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.1, random_state=0)

# Train the Logistic Regression model
np = GaussianNB()
np = np.fit(x_train, y_train)

# Make predictions on the test set
y_pred = np.predict(x_test)

# Evaluate the model
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
np.predict(sc.fit_transform([[1,19,19000]]))

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
Accuracy Score: 0.925
Confusion Matrix:
 [[30  2]
 [ 1  7]]


array([0])